import sys

MYBOT_FILE = "depth4_lines_bot.txt"
PYTHON_FILE = "depth4_lines.txt"

def load_file(filename):
    with open(filename, "r") as f:
        # Strip whitespace and ignore empty lines
        return set(line.strip() for line in f if line.strip())

def main():
    mybot_moves = load_file(MYBOT_FILE)
    python_moves = load_file(PYTHON_FILE)

    print("MyBot total lines :", len(mybot_moves))
    print("Python total lines:", len(python_moves))
    print()

    # Moves your bot generated but python did NOT
    extra_moves = mybot_moves - python_moves

    # Moves python generated but your bot did NOT
    missing_moves = python_moves - mybot_moves

    print("Extra moves (BUG in your bot):", len(extra_moves))
    print("Missing moves:", len(missing_moves))
    print()

    if extra_moves:
        print("=== Moves generated by YOUR BOT but NOT in Python ===")
        for move in sorted(extra_moves):
            print(move)

    if missing_moves:
        print("\n=== Moves missing in YOUR BOT ===")
        for move in sorted(missing_moves):
            print(move)

    if not extra_moves and not missing_moves:
        print("✅ PERFECT MATCH — Move generation is correct.")

if __name__ == "__main__":
    main()